### ISSUE TITLE
APY leaders endpoint returning entries with low aprEst values

### ISSUE THREAD

**Issue by benwolski** [CrocSwap/graphcache-go#11]
Results for queries to the pool_position_apy_leaders endpoint do not appear to be ordered by aprEst:

https://ambindexer.net/gcgo/pool_position_apy_leaders?chainId=0x1&base=0x0000000000000000000000000000000000000000&quote=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&poolIdx=420&n=10

These lists should be roughly the same, when the ranges table is sorted by APR:

![image](https://github.com/CrocSwap/graphcache-go/assets/570819/725b4df5-a121-4dd9-9f77-073d0c71a378)
![image](https://github.com/CrocSwap/graphcache-go/assets/570819/696f3d3c-0bec-4aef-97ff-bdfccb70b0fb)

**Comment by PaulMcInnis** [comment]
`high-prio`
