### ISSUE TITLE
Pool Stats Endpoint Returning Inconsistent Value for lastPriceIndic resulting in inconsistent 24 hr price change

### ISSUE THREAD

**Issue by benwolski** [CrocSwap/graphcache-go#2]
![image](https://github.com/CrocSwap/graphcache-go/assets/570819/69733ed5-dd6e-4567-9f4b-374023a2e1ea)
![image](https://github.com/CrocSwap/graphcache-go/assets/570819/3a80c70a-d451-4ea1-ae46-380e5188f3fe)

**Comment by benwolski** [comment]
These inconsistencies result in values like -99.84%and +62,999.51% appearing
![image](https://github.com/CrocSwap/graphcache-go/assets/570819/e6a4ea4d-ca58-4783-8cb4-bee2e6644bc1)
![image](https://github.com/CrocSwap/graphcache-go/assets/570819/5ba77c46-3af7-4d52-92f5-e46d0689a2d2)

**Comment by benwolski** [comment]
This appears to still be an issue to a certain extent: 

![image](https://github.com/CrocSwap/graphcache-go/assets/570819/97652fb6-8acc-4d65-bb1f-62e2c917c789)

**Comment by PaulMcInnis** [comment]
`high-prio`

**Comment by PaulMcInnis** [comment]
working theory: there was some sort of sandwhich attack for when pool price shifts suddenly, and when we go back 24 hrs we're somehow picking that swap and comparing the two and it looks huge

**Comment by PaulMcInnis** [comment]
potential solution: use an average vs looking at a single swap

**Comment by PaulMcInnis** [comment]
@yharsono when ur back

**Comment by PaulMcInnis** [comment]
I'll investigate

**Comment by cadezacharias-hype** [comment]
https://ambindexer.net/gcgo/pool_stats?base=0x0000000000000000000000000000000000000000&quote=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&poolIdx=420&chainId=0x1

**Comment by PaulMcInnis** [comment]
Relates to #16 

Looking at porting our old filter from existing `graphcache` server
